# Generated by Django 5.0.3 on 2024-05-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_account_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.AddField(
            model_name='account',
            name='acc_type',
            field=models.CharField(default='savings', max_length=500),
        ),
        migrations.AddField(
            model_name='account',
            name='account_no',
            field=models.BigIntegerField(default=123456),
        ),
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.IntegerField(default=1000),
        ),
    ]
